development:
  adapter: postgresql
  encoding: unicode
  database: simple_blog_development
  pool: 5
  username: german
  password: hardpass213

test:
  adapter: postgresql
  encoding: unicode
  database: simple_blog_test
  pool: 5
  username: german
  password: hardpass213

production:
  adapter: postgresql
  encoding: unicode
  database: simple_blog_production
  pool: 5
  username: german
  password: hardpass213
